Add local registry initialization to Makefile
vmware-tanzu/build-tooling-for-integrations pull request #39
Opened 2022-11-17 16:29 UTC by jmoroski

# Description
This change adds a make target to create a local Docker registry for pushing and pulling packages without requiring additional configuration or external registry access.

This change also introduces a bootstrap target that aggregates the environment and project initialization process across a few finer-grained targets. The behavior of this new target is as follows:
1. Start a docker registry container locally (if necessary) a. This can be bypassed in a CI environment
2. Check for the presence of a build container Dockerfile in working dir a. Prompt to overwrite if found b. Add build container Dockerfile if not present or if overwriting
3. Pull the Tanzu packaging image

Other minor changes:
* Changed how help was being generated to support multiline text and classification of targets
* Made help the default target

Fixes #25

## Change Details
Check all that apply:
- [x] New feature 
- [ ] Bug fix 
- [ ] Non-code change 
- [x] Non-breaking change 
- [ ] Breaking change
- [x] Requires a documentation change

## Release Note

```release-note
Adds a local registry via the bootstrap target to simplify local development flows.
```

# How Has This Been Tested?
1. Ran the make bootstrap target in a new project. Verified that a local registry container was started, a Dockerfile and lint configuration were added to the root diretory of the project, and the package image was pulled down
2. Ran make boostrap again. Verified that the registry container was identified to be already running. Verified that I was prompted to overwrite an existing Dockerfile. Selected 'N' and verified that the Dockerfile was unchanged.
3. Ran make bootstrap again. Verified that I was prompted to overwrite existing Dockerfile. Selected 'Y' and verified that the Dockerfile was overwritten to the original state.
4. Ran both make and make help. Verified that the help message was output in both cases.

# Checklist:
- [x] My code follows the [Contribution and Style guidelines](../../CONTRIBUTING.md) of this project
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have added test details that prove my fix is effective or that my feature works

2022-12-06 21:49 UTC, yharish991 requested changes

2022-12-07 13:18 UTC, jmoroski commented on templates/Makefile
> +## Project Targets
Absolutely. I'll make that change

2022-12-07 13:21 UTC, jmoroski commented on templates/Makefile
> +REGISTRY_PORT := 5000
Good to know. I'll find something that works as a better universal default.

2022-12-08 13:42 UTC, jmoroski commented on templates/Makefile
> +REGISTRY_PORT := 5000
Updated to use port 8000 which seems to align with where docker is headed to resolve this issue (https://github.com/docker/docs/issues/14226)

2022-12-08 13:42 UTC, jmoroski commented on templates/Makefile
> +## Project Targets
changed

2022-12-11 23:09 UTC, yharish991 approved these changes

2022-12-15 21:43 UTC, merged