generate and copy the binaries back to the host machine
vmware-tanzu/build-tooling-for-integrations pull request #45
Opened 2022-12-19 22:24 UTC by yharish991

# Description
This PR adds a make target `generate-binary` that generates binaries and copies them back to the host machine

Fixes https://github.com/vmware-tanzu/build-tooling-for-integrations/issues/42

## Change Details
Check all that apply:
- [x] New feature 
- [ ] Bug fix 
- [ ] Non-code change 
- [ ] Non-breaking change 
- [ ] Breaking change
- [ ] Requires a documentation change

## Release Note

```release-note
```

# How Has This Been Tested?
Ran the make target `generate-binary` and verified that the binary is created for the go module

# Checklist:
- [x] My code follows the [Contribution and Style guidelines](../../CONTRIBUTING.md) of this project
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have added test details that prove my fix is effective or that my feature works

2023-01-05 14:54 UTC, yharish991 commented on templates/Makefile
> +generate-binary:
rename this target to `binary-build`

2023-01-10 20:31 UTC, jmoroski requested changes

2023-01-10 20:31 UTC, jmoroski commented on templates/Dockerfile
> +COPY --from=unit-test /out/cover.out /cover.out
can we put generated artifacts into a build/ directory for easier management.
* build/bin
* build/reports
* build/coverage

etc.

2023-01-10 20:31 UTC, jmoroski commented on templates/Makefile
> +.PHONY: binary-build
this code doesn't seem to match the PR description

2023-01-10 20:56 UTC, yharish991 commented on templates/Makefile
> +.PHONY: binary-build
my bad, i forgot to update the pr description after we discussed to rename `generate-binary` to `binary-build`, will update the pr description

2023-01-16 19:29 UTC, yharish991 commented on templates/Dockerfile
> +COPY --from=unit-test /out/cover.out /cover.out
done

2023-01-16 19:37 UTC, yharish991 commented on templates/Dockerfile
> +COPY --from=unit-test /out/cover.out /cover.out
this is how it would look in a multi module project, let me know what you think
```
build
├── module1
│   ├── bin
│   │   └── manager
│   └── coverage
│       └── cover.out
└── module2
    ├── bin
    │   └── manager
    └── coverage
        └── cover.out
```

2023-01-17 19:57 UTC, jmoroski commented on templates/Dockerfile
> +COPY --from=unit-test /out/cover.out /cover.out
I think that's good as a starting point, thanks.

2023-01-17 21:27 UTC, rajathagasthya commented on templates/Dockerfile
> +FROM bin-unix AS bin-darwin
Just curious why there is no `COPY` for linux and darwin here. Does Dockerfile take care of this automatically based on L64-L65?

2023-01-17 21:30 UTC, rajathagasthya commented on templates/Makefile
> +PLATFORM=local
Should this be defaulted to an actual `os/arch` value?

2023-01-17 21:45 UTC, yharish991 commented on templates/Dockerfile
> +FROM bin-unix AS bin-darwin
it's being done in line 65, we are basically naming the `bin-unix` stage as `bin-linux` and `bin-darwin` lines L64-L65

2023-01-17 21:47 UTC, yharish991 commented on templates/Dockerfile
> +FROM bin-unix AS bin-darwin
yes, you are right.. lines 67 and 68 we are basically naming `bin-unix` as `bin-linux` and `bin-darwin`

2023-01-17 21:54 UTC, yharish991 commented on templates/Makefile
> +PLATFORM=local
this is for building binaries on the local machine(can be any linux/mac/windows machine)
for building images we default it to linux/amd64 here https://github.com/vmware-tanzu/build-tooling-for-integrations/pull/45/files#diff-0e249a8ab955b4a02a0d64f54e3f6b4711801005792f9b286e5b16405e7381feR160

2023-01-17 21:55 UTC, jmoroski approved these changes
I feel like there will be further iterations to make on this, but it's a good interim step to publish a new image from.

2023-01-17 22:18 UTC, rajathagasthya commented on templates/Makefile
> +PLATFORM=local
My question was because `${PLATFORM}` is being passed as an arg in [L170](https://github.com/vmware-tanzu/build-tooling-for-integrations/pull/45/files#diff-0e249a8ab955b4a02a0d64f54e3f6b4711801005792f9b286e5b16405e7381feR170).

2023-01-20 19:59 UTC, rajathagasthya approved these changes

2023-01-20 20:24 UTC, merged