Run lint and test for Tanzu CLI plugins
vmware-tanzu/build-tooling-for-integrations pull request #71
Opened 2023-04-21 02:44 UTC by codegold79

# Description
_Include a summary of the change. If this change fixes an issue, indicate that on the `Fixes` line. Briefly include
relevant context and motivation._

Enable running linter and test (vet and fmt) for Tanzu CLI plugins.

Fixes #{issue}

## Change Details
Check all that apply:
- [x] New feature 
- [ ] Bug fix 
- [ ] Non-code change 
- [ ] Non-breaking change 
- [ ] Breaking change
- [ ] Requires a documentation change

## Release Note

```release-note
Enable running linter and test (vet and fmt) for Tanzu CLI plugins.
```

# How Has This Been Tested?
_Describe any testing done to verify changes. Provide enough detail that tests can be reproduced._

# Checklist:
- [ ] My code follows the [Contribution and Style guidelines](../../CONTRIBUTING.md) of this project
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added test details that prove my fix is effective or that my feature works

2023-04-24 18:46 UTC, yharish991 requested changes

2023-04-24 19:39 UTC, rajathagasthya commented on examples/multi-module-integration/cmd/plugin/plugin-demo-bar/main.go
> +// Copyright 2021 VMware, Inc. All Rights Reserved.
`s/2021/2023`

2023-04-24 19:39 UTC, rajathagasthya commented on examples/multi-module-integration/cmd/plugin/plugin-demo-foo/main.go
> +// Copyright 2022 VMware, Inc. All Rights Reserved.
`s/2022/2023`

2023-04-24 23:29 UTC, codegold79 commented on examples/multi-module-integration/cmd/plugin/plugin-demo-bar/main.go
> +// Copyright 2021 VMware, Inc. All Rights Reserved.
done

2023-04-24 23:29 UTC, codegold79 commented on examples/multi-module-integration/cmd/plugin/plugin-demo-foo/main.go
> +// Copyright 2022 VMware, Inc. All Rights Reserved.
done

2023-04-24 23:29 UTC, codegold79 commented on templates/Makefile
> +	# $(DOCKER) build --network=host . -f Dockerfile \
good catch. done.

2023-04-24 23:33 UTC, yharish991 approved these changes

2023-04-25 15:33 UTC, rajathagasthya approved these changes

2023-04-25 15:54 UTC, merged